[package]
name = "ngx_test_suite"
version = "0.2.0"
authors = ["Sehyo Chang   sehyo@nginx.com"]


[dependencies]
ngx-sys   =  { path = "../ngx-sys" , version = "0.2.0" }
ngx-module   =  { path = "../ngx-module" , version = "0.2.0" }


