[package]
name = "ngx-sys"
version = "0.2.0"
authors = ["Sehyo Chang   sehyo@nginx.com"]

[lib]
doctest = false
test = true
crate-type = ["staticlib","rlib"]


[build-dependencies]
bindgen = "0.35.0"


